version: '3.8'

services:
  hsa108_nginx:
    image: nginx:1.21.6-alpine
    ports: 
      - 8077:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/images:/images